create table Courses (
	department VARCHAR(4),
	code VARCHAR(2),
	description VARCHAR(255),
	minStudents INT,
	maxStudents INT
);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CHEM', '4C', 'Distributed regional middleware', 4, 19);
insert into Courses (department, code, description, minStudents, maxStudents) values ('MATH', '3D', 'Synchronised fault-tolerant paradigm', 2, 19);
insert into Courses (department, code, description, minStudents, maxStudents) values ('PHYS', '3B', 'Public-key discrete matrix', 2, 14);
insert into Courses (department, code, description, minStudents, maxStudents) values ('MATH', '2D', 'Cross-platform optimizing focus group', 4, 14);
insert into Courses (department, code, description, minStudents, maxStudents) values ('LANG', '2B', 'Expanded intangible benchmark', 4, 17);
insert into Courses (department, code, description, minStudents, maxStudents) values ('PSYC', '1D', 'Total 3rd generation firmware', 2, 11);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ANTH', '1D', 'Re-engineered upward-trending analyzer', 3, 19);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ECON', '2B', 'Vision-oriented zero tolerance local area network', 3, 8);
insert into Courses (department, code, description, minStudents, maxStudents) values ('EECS', '4C', 'Public-key neutral utilisation', 3, 8);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ASTR', '2D', 'Implemented uniform service-desk', 2, 7);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CIM', '3B', 'Up-sized intermediate adapter', 3, 20);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ECON', '3A', 'Down-sized modular process improvement', 5, 20);
insert into Courses (department, code, description, minStudents, maxStudents) values ('HUM', '4D', 'Up-sized 24 hour concept', 5, 10);
insert into Courses (department, code, description, minStudents, maxStudents) values ('PHYS', '3A', 'Front-line content-based artificial intelligence', 4, 7);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CRTV', '4B', 'Re-contextualized 6th generation intranet', 4, 19);
insert into Courses (department, code, description, minStudents, maxStudents) values ('DES', '3A', 'Implemented system-worthy encryption', 4, 9);
insert into Courses (department, code, description, minStudents, maxStudents) values ('PHYS', '4C', 'Synergized upward-trending throughput', 3, 15);
insert into Courses (department, code, description, minStudents, maxStudents) values ('EECS', '1C', 'Decentralized systematic encoding', 2, 8);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ENG', '1B', 'Upgradable leading edge parallelism', 2, 7);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ACC', '1D', 'Monitored asynchronous interface', 3, 18);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ENV', '3D', 'Object-based 24 hour approach', 2, 14);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CIM', '1D', 'Team-oriented intangible interface', 5, 20);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ECON', '3A', 'Persistent leading edge knowledge base', 4, 17);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ENV', '2A', 'Virtual regional benchmark', 2, 7);
insert into Courses (department, code, description, minStudents, maxStudents) values ('GEO', '1A', 'Cross-group non-volatile instruction set', 4, 20);
insert into Courses (department, code, description, minStudents, maxStudents) values ('DES', '3D', 'Automated asymmetric website', 5, 13);
insert into Courses (department, code, description, minStudents, maxStudents) values ('PHYS', '1B', 'Customizable 6th generation solution', 2, 13);
insert into Courses (department, code, description, minStudents, maxStudents) values ('GEO', '3A', 'Up-sized foreground frame', 4, 10);
insert into Courses (department, code, description, minStudents, maxStudents) values ('DES', '1B', 'Assimilated discrete initiative', 5, 20);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ART', '2D', 'Stand-alone modular website', 4, 7);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ENV', '2A', 'Multi-lateral 24 hour encoding', 2, 10);
insert into Courses (department, code, description, minStudents, maxStudents) values ('EECS', '2B', 'Programmable client-driven flexibility', 5, 19);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CHEM', '4D', 'Grass-roots logistical projection', 5, 16);
insert into Courses (department, code, description, minStudents, maxStudents) values ('MUS', '1B', 'Synergized cohesive infrastructure', 3, 9);
insert into Courses (department, code, description, minStudents, maxStudents) values ('MATH', '1A', 'Profit-focused transitional solution', 4, 16);
insert into Courses (department, code, description, minStudents, maxStudents) values ('DES', '1C', 'Secured incremental database', 5, 10);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ANTH', '3B', 'Progressive value-added encryption', 5, 18);
insert into Courses (department, code, description, minStudents, maxStudents) values ('NUR', '2D', 'Optimized well-modulated benchmark', 4, 12);
insert into Courses (department, code, description, minStudents, maxStudents) values ('NUR', '1D', 'Decentralized impactful hierarchy', 4, 11);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CHEM', '2B', 'Virtual homogeneous superstructure', 3, 14);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ACC', '1D', 'Expanded reciprocal ability', 3, 16);
insert into Courses (department, code, description, minStudents, maxStudents) values ('GEO', '2B', 'Realigned demand-driven complexity', 2, 12);
insert into Courses (department, code, description, minStudents, maxStudents) values ('HIST', '4B', 'Organic interactive initiative', 3, 14);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ENV', '4C', 'Secured didactic monitoring', 2, 9);
insert into Courses (department, code, description, minStudents, maxStudents) values ('LANG', '4A', 'Virtual neutral initiative', 5, 11);
insert into Courses (department, code, description, minStudents, maxStudents) values ('DES', '3B', 'Re-engineered methodical superstructure', 5, 8);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ART', '3C', 'Object-based disintermediate algorithm', 5, 16);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CHEM', '1B', 'Proactive contextually-based functionalities', 3, 14);
insert into Courses (department, code, description, minStudents, maxStudents) values ('MUS', '1B', 'Vision-oriented tertiary model', 2, 14);
insert into Courses (department, code, description, minStudents, maxStudents) values ('MUS', '1C', 'Multi-channelled web-enabled framework', 3, 13);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ASTR', '2C', 'Configurable contextually-based help-desk', 2, 15);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CIS', '1C', 'User-centric asynchronous matrix', 4, 8);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ART', '4A', 'Universal cohesive utilisation', 3, 18);
insert into Courses (department, code, description, minStudents, maxStudents) values ('HUM', '4B', 'Mandatory systematic architecture', 4, 19);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ART', '4B', 'Polarised modular hierarchy', 5, 19);
insert into Courses (department, code, description, minStudents, maxStudents) values ('LANG', '2A', 'Decentralized leading edge projection', 5, 12);
insert into Courses (department, code, description, minStudents, maxStudents) values ('HIST', '3B', 'Digitized scalable open architecture', 2, 16);
insert into Courses (department, code, description, minStudents, maxStudents) values ('DES', '1C', 'Self-enabling incremental migration', 5, 15);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ANTH', '2D', 'Digitized human-resource analyzer', 3, 13);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ECON', '1C', 'Distributed bifurcated throughput', 2, 16);
insert into Courses (department, code, description, minStudents, maxStudents) values ('HIST', '2A', 'Future-proofed next generation internet solution', 2, 8);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CIS', '2D', 'Monitored real-time contingency', 5, 10);
insert into Courses (department, code, description, minStudents, maxStudents) values ('BUS', '4C', 'Public-key real-time knowledge base', 3, 15);
insert into Courses (department, code, description, minStudents, maxStudents) values ('GEO', '4D', 'Organized systemic intranet', 3, 7);
insert into Courses (department, code, description, minStudents, maxStudents) values ('MUS', '3A', 'Seamless multimedia Graphical User Interface', 4, 7);
insert into Courses (department, code, description, minStudents, maxStudents) values ('NUR', '1D', 'Expanded uniform hub', 5, 17);
insert into Courses (department, code, description, minStudents, maxStudents) values ('DES', '2A', 'Object-based encompassing projection', 3, 14);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ECON', '1A', 'Optional bifurcated paradigm', 3, 13);
insert into Courses (department, code, description, minStudents, maxStudents) values ('PSYC', '4C', 'Profound bifurcated local area network', 5, 17);
insert into Courses (department, code, description, minStudents, maxStudents) values ('MUS', '2D', 'Switchable intermediate standardization', 4, 13);
insert into Courses (department, code, description, minStudents, maxStudents) values ('HUM', '1C', 'Managed systemic solution', 4, 20);
insert into Courses (department, code, description, minStudents, maxStudents) values ('HUM', '2A', 'Versatile zero tolerance budgetary management', 2, 19);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ACC', '2B', 'Switchable discrete frame', 2, 20);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CS', '3C', 'Digitized bandwidth-monitored orchestration', 2, 14);
insert into Courses (department, code, description, minStudents, maxStudents) values ('HIST', '2B', 'Programmable intangible algorithm', 2, 17);
insert into Courses (department, code, description, minStudents, maxStudents) values ('BUS', '2A', 'Synergistic exuding access', 4, 18);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ART', '1A', 'Compatible modular superstructure', 4, 14);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CIM', '3C', 'Up-sized neutral concept', 5, 16);
insert into Courses (department, code, description, minStudents, maxStudents) values ('PHYS', '4A', 'Customer-focused background projection', 3, 12);
insert into Courses (department, code, description, minStudents, maxStudents) values ('NUR', '1D', 'Integrated upward-trending info-mediaries', 5, 15);
insert into Courses (department, code, description, minStudents, maxStudents) values ('GEO', '1C', 'Enhanced bandwidth-monitored knowledge base', 2, 11);
insert into Courses (department, code, description, minStudents, maxStudents) values ('MUS', '2A', 'Implemented secondary installation', 3, 8);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ASTR', '1B', 'Optional impactful monitoring', 4, 12);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ACC', '1B', 'De-engineered bi-directional approach', 4, 13);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ACC', '3C', 'Compatible full-range alliance', 2, 16);
insert into Courses (department, code, description, minStudents, maxStudents) values ('NUR', '4C', 'Grass-roots intangible parallelism', 4, 19);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CIS', '3B', 'Enhanced multi-tasking Graphic Interface', 3, 10);
insert into Courses (department, code, description, minStudents, maxStudents) values ('HUM', '3A', 'Streamlined multi-state alliance', 3, 8);
insert into Courses (department, code, description, minStudents, maxStudents) values ('EECS', '2B', 'Organized interactive website', 5, 18);
insert into Courses (department, code, description, minStudents, maxStudents) values ('BIO', '1C', 'Ergonomic stable paradigm', 5, 20);
insert into Courses (department, code, description, minStudents, maxStudents) values ('MUS', '2C', 'Multi-channelled zero defect emulation', 4, 16);
insert into Courses (department, code, description, minStudents, maxStudents) values ('HIST', '2D', 'Profound demand-driven hardware', 3, 13);
insert into Courses (department, code, description, minStudents, maxStudents) values ('BUS', '3D', 'Optimized mission-critical projection', 5, 11);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CIS', '2C', 'Visionary explicit groupware', 4, 17);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ECON', '2D', 'Enterprise-wide full-range firmware', 2, 7);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CIM', '3D', 'Devolved clear-thinking intranet', 5, 18);
insert into Courses (department, code, description, minStudents, maxStudents) values ('ECON', '1B', 'Future-proofed 5th generation monitoring', 4, 12);
insert into Courses (department, code, description, minStudents, maxStudents) values ('LANG', '3B', 'Cross-group motivating migration', 5, 16);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CRTV', '4B', 'Reverse-engineered discrete encryption', 3, 11);
insert into Courses (department, code, description, minStudents, maxStudents) values ('CRTV', '3C', 'Expanded incremental internet solution', 4, 19);
