create table Faculty (
	firstName VARCHAR(50),
	middleName VARCHAR(50),
	lastName VARCHAR(50),
	email VARCHAR(50),
	telephone VARCHAR(50),
	street VARCHAR(50),
	city VARCHAR(50),
	state VARCHAR(50),
	zip VARCHAR(50),
	hireDate DATE,
	isTenured VARCHAR(50),
	taughtCourses VARCHAR(255)
);
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Daven', 'Gunar', 'Andree', 'gandree0@studiopress.com', '206-537-5858', 'Kipling', 'Seattle', 'WA', '98133', '1983-06-04', true, '[{"department":"MATH","code":"1B"},{"department":"MATH","code":"1D"},{"department":"PHYS","code":"2A"},{"department":"CRTV","code":"3C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Winifield', 'Goldie', 'Cansdale', 'gcansdale1@hp.com', '702-534-2306', 'Golf', 'Las Vegas', 'NV', '89160', '1973-06-07', false, '[{"department":"NUR","code":"4A"},{"department":"EECS","code":"2D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kassi', 'Kandace', 'De Micoli', 'kdemicoli2@tripod.com', '713-222-6418', 'High Crossing', 'Houston', 'TX', '77250', '1993-07-08', true, '[{"department":"EECS","code":"4A"},{"department":"PSYC","code":"1A"},{"department":"EECS","code":"2C"},{"department":"HUM","code":"2D"},{"department":"MUS","code":"4C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Isidore', 'Nonna', 'Coleiro', 'ncoleiro3@bluehost.com', '863-111-4252', 'Maple Wood', 'Winter Haven', 'FL', '33884', '2019-07-09', false, '[{"department":"CS","code":"3A"},{"department":"LANG","code":"2C"},{"department":"PHYS","code":"3C"},{"department":"ENV","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Keen', 'Consalve', 'Fortesquieu', 'cfortesquieu4@chronoengine.com', '559-668-9857', 'Hagan', 'Fresno', 'CA', '93740', '2007-12-31', false, '[{"department":"ACC","code":"1C"},{"department":"BUS","code":"2C"},{"department":"HUM","code":"1B"},{"department":"ASTR","code":"2D"},{"department":"LANG","code":"2B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Neilla', 'Bobbi', 'Cardenas', 'bcardenas5@booking.com', '701-256-0136', 'Milwaukee', 'Fargo', 'ND', '58122', '1987-05-06', true, '[{"department":"ENG","code":"2D"},{"department":"HUM","code":"4A"},{"department":"ENG","code":"3A"},{"department":"BIO","code":"4B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Constantino', 'Lydie', 'Staresmeare', 'lstaresmeare6@walmart.com', '919-776-8156', 'Autumn Leaf', 'Raleigh', 'NC', '27615', '2006-10-03', true, '[{"department":"NUR","code":"4D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Ursulina', 'Marieann', 'Gjerde', 'mgjerde7@altervista.org', '202-773-3170', 'Northview', 'Washington', 'DC', '20310', '1990-01-19', false, '[{"department":"CRTV","code":"3D"},{"department":"MATH","code":"3D"},{"department":"ASTR","code":"2C"},{"department":"CIS","code":"2A"},{"department":"ART","code":"2C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Gabrila', 'Aarika', 'Scandred', 'ascandred8@tmall.com', '806-607-5178', 'Ridgeway', 'Lubbock', 'TX', '79415', '2005-11-27', false, '[{"department":"ECON","code":"2D"},{"department":"HUM","code":"3A"},{"department":"HUM","code":"4B"},{"department":"DES","code":"3B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Lilli', 'Ev', 'Cornehl', 'ecornehl9@yale.edu', '915-965-8864', 'Elka', 'El Paso', 'TX', '79968', '1972-08-10', true, '[{"department":"ENG","code":"2D"},{"department":"NUR","code":"3A"},{"department":"NUR","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Joanna', 'Ruperto', 'Hassell', 'rhassella@boston.com', '859-449-5960', 'Westend', 'Lexington', 'KY', '40596', '1988-01-12', false, '[{"department":"LANG","code":"3B"},{"department":"BIO","code":"3D"},{"department":"ENV","code":"1D"},{"department":"MATH","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Tarah', 'Calla', 'Leagas', 'cleagasb@walmart.com', '937-793-2962', 'Clemons', 'Dayton', 'OH', '45432', '1970-02-18', false, '[{"department":"CS","code":"3D"},{"department":"EECS","code":"1D"},{"department":"GEO","code":"2B"},{"department":"BIO","code":"3C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Laurel', 'Gena', 'McNicol', 'gmcnicolc@sphinn.com', '727-619-3650', 'Menomonie', 'Saint Petersburg', 'FL', '33715', '1974-01-30', true, '[{"department":"CIS","code":"1B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Demeter', 'Nadia', 'Stapels', 'nstapelsd@scribd.com', '716-978-0946', 'Lunder', 'Buffalo', 'NY', '14276', '2004-11-27', true, '[{"department":"HIST","code":"3B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Paul', 'Corbet', 'Kimbrough', 'ckimbroughe@netscape.com', '323-345-0480', 'Park Meadow', 'Los Angeles', 'CA', '90005', '2007-08-17', true, '[{"department":"CHEM","code":"2D"},{"department":"DES","code":"2B"},{"department":"ACC","code":"3D"},{"department":"ART","code":"3A"},{"department":"NUR","code":"3B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Trever', 'Alfy', 'Belch', 'abelchf@facebook.com', '404-787-5244', 'Forest Dale', 'Atlanta', 'GA', '30323', '1986-11-26', false, '[{"department":"NUR","code":"1B"},{"department":"ENG","code":"4D"},{"department":"HIST","code":"4B"},{"department":"LANG","code":"4B"},{"department":"CRTV","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Anders', 'Valina', 'Grason', 'vgrasong@businesswire.com', '513-146-1987', 'Delaware', 'Cincinnati', 'OH', '45208', '1990-04-12', false, '[{"department":"LANG","code":"1A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Cris', 'Ethelyn', 'Mapham', 'emaphamh@google.nl', '207-370-1687', 'Union', 'Portland', 'ME', '04109', '1999-10-02', false, '[{"department":"CRTV","code":"3A"},{"department":"ANTH","code":"2A"},{"department":"DES","code":"1C"},{"department":"CIM","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Wilfrid', 'Rice', 'Abramov', 'rabramovi@e-recht24.de', '240-593-1405', 'Portage', 'Frederick', 'MD', '21705', '1993-11-01', false, '[{"department":"LANG","code":"1B"},{"department":"CS","code":"1A"},{"department":"PSYC","code":"4C"},{"department":"MUS","code":"4A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Winna', 'Gabie', 'Donwell', 'gdonwellj@wired.com', '469-172-0512', 'Porter', 'Dallas', 'TX', '75205', '1990-11-06', true, '[{"department":"NUR","code":"2A"},{"department":"ANTH","code":"4C"},{"department":"PHYS","code":"2A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kimberli', 'Chrystel', 'Brisbane', 'cbrisbanek@ihg.com', '862-468-5420', 'Mockingbird', 'Newark', 'NJ', '07188', '1989-11-16', false, '[{"department":"ACC","code":"4B"},{"department":"ENV","code":"3C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Claudell', 'Gianina', 'Powderham', 'gpowderhaml@nasa.gov', '702-939-3839', 'High Crossing', 'Las Vegas', 'NV', '89135', '1998-09-26', true, '[{"department":"ECON","code":"1D"},{"department":"CHEM","code":"2A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Gilli', 'Siouxie', 'Aguilar', 'saguilarm@google.cn', '561-764-0418', 'Fallview', 'West Palm Beach', 'FL', '33416', '2015-11-12', true, '[{"department":"HUM","code":"1A"},{"department":"PSYC","code":"3B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Daffi', 'Brenna', 'Champerlen', 'bchamperlenn@irs.gov', '719-762-9500', 'Pearson', 'Colorado Springs', 'CO', '80940', '2019-08-31', false, '[{"department":"ART","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Wenona', 'Rinaldo', 'Donnellan', 'rdonnellano@sphinn.com', '205-288-8992', 'Coolidge', 'Birmingham', 'AL', '35290', '1970-03-30', false, '[{"department":"CS","code":"3A"},{"department":"ART","code":"4B"},{"department":"LANG","code":"1C"},{"department":"CIS","code":"4A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Damien', 'Clovis', 'Cornew', 'ccornewp@census.gov', '559-813-3795', 'Bobwhite', 'Fresno', 'CA', '93773', '2022-02-22', false, '[{"department":"CRTV","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kirk', 'Lefty', 'Fowley', 'lfowleyq@surveymonkey.com', '786-472-4032', 'Grover', 'Miami', 'FL', '33158', '1988-03-01', true, '[{"department":"DES","code":"4A"},{"department":"HUM","code":"4B"},{"department":"EECS","code":"4D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Conrade', 'Loreen', 'Ionnisian', 'lionnisianr@mlb.com', '816-671-6606', 'Mockingbird', 'Shawnee Mission', 'KS', '66210', '2008-06-20', false, '[{"department":"CRTV","code":"2B"},{"department":"ART","code":"1B"},{"department":"ECON","code":"2C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Port', 'Jonis', 'Babonau', 'jbabonaus@admin.ch', '713-598-5350', 'Daystar', 'Houston', 'TX', '77234', '2018-11-27', false, '[{"department":"MUS","code":"3B"},{"department":"DES","code":"2A"},{"department":"EECS","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Milka', 'Thorny', 'Selby', 'tselbyt@shop-pro.jp', '334-552-2724', 'Utah', 'Montgomery', 'AL', '36104', '1993-09-19', false, '[{"department":"CRTV","code":"2A"},{"department":"CRTV","code":"4A"},{"department":"ACC","code":"1A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Jo-ann', 'Timoteo', 'Moscone', 'tmosconeu@rediff.com', '406-401-0443', 'Esch', 'Billings', 'MT', '59105', '2000-11-22', false, '[{"department":"LANG","code":"2D"},{"department":"ART","code":"1A"},{"department":"ANTH","code":"4B"},{"department":"PSYC","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Irving', 'Ilario', 'Gladden', 'igladdenv@diigo.com', '562-764-5076', 'Center', 'Los Angeles', 'CA', '90010', '1996-05-07', true, '[{"department":"ECON","code":"1A"},{"department":"CHEM","code":"2A"},{"department":"CRTV","code":"4C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Darsie', 'Georgianne', 'Dannehl', 'gdannehlw@arizona.edu', '915-326-1831', 'Susan', 'El Paso', 'TX', '79905', '1990-06-08', true, '[{"department":"MATH","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Jilli', 'Vi', 'Robardley', 'vrobardleyx@hhs.gov', '918-428-1974', 'Everett', 'Tulsa', 'OK', '74193', '1999-11-09', false, '[{"department":"PSYC","code":"1D"},{"department":"MUS","code":"1A"},{"department":"CRTV","code":"2D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kellby', 'Karlene', 'Greedyer', 'kgreedyery@nationalgeographic.com', '312-808-8745', '8th', 'Chicago', 'IL', '60657', '1994-02-01', true, '[{"department":"HUM","code":"2B"},{"department":"PHYS","code":"1B"},{"department":"ENV","code":"4C"},{"department":"CS","code":"2D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Bartlet', 'Lesli', 'Cheverton', 'lchevertonz@apple.com', '434-771-2280', 'Longview', 'Durham', 'NC', '27705', '1996-05-11', true, '[{"department":"NUR","code":"3B"},{"department":"MATH","code":"1D"},{"department":"ACC","code":"1D"},{"department":"BIO","code":"4B"},{"department":"ACC","code":"2B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kerwinn', 'Bink', 'Gooders', 'bgooders10@time.com', '806-129-8176', 'Green', 'Amarillo', 'TX', '79116', '1993-04-03', true, '[{"department":"LANG","code":"3D"},{"department":"BIO","code":"3C"},{"department":"GEO","code":"4D"},{"department":"PSYC","code":"1B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Halsy', 'Boniface', 'Persent', 'bpersent11@rakuten.co.jp', '806-998-2081', 'Heath', 'Lubbock', 'TX', '79452', '1977-10-01', true, '[{"department":"ACC","code":"2C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Shea', 'Tandy', 'Montrose', 'tmontrose12@cnet.com', '832-855-2936', 'Dwight', 'Houston', 'TX', '77010', '1997-03-30', true, '[{"department":"MUS","code":"3A"},{"department":"CHEM","code":"3D"},{"department":"PHYS","code":"3A"},{"department":"DES","code":"3A"},{"department":"ASTR","code":"2C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Leontyne', 'Jaclin', 'Godain', 'jgodain13@kickstarter.com', '812-602-5842', 'Warner', 'Jeffersonville', 'IN', '47134', '2004-08-01', false, '[{"department":"EECS","code":"1D"},{"department":"MUS","code":"4B"},{"department":"HIST","code":"3D"},{"department":"MUS","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kerrie', 'Mandel', 'Euston', 'meuston14@trellian.com', '772-377-3151', 'Schurz', 'Fort Pierce', 'FL', '34949', '1995-04-29', true, '[{"department":"ART","code":"4C"},{"department":"HUM","code":"1D"},{"department":"NUR","code":"2C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kalil', 'Michele', 'Scrane', 'mscrane15@nature.com', '513-574-9626', 'Susan', 'Cincinnati', 'OH', '45203', '1977-03-07', true, '[{"department":"CRTV","code":"4C"},{"department":"CRTV","code":"4A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Angelia', 'Rose', 'Ownsworth', 'rownsworth16@nasa.gov', '973-559-2495', 'Golden Leaf', 'Paterson', 'NJ', '07505', '1970-12-01', true, '[{"department":"BUS","code":"3B"},{"department":"CRTV","code":"1C"},{"department":"CS","code":"3B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Jocelyne', 'Coraline', 'Calway', 'ccalway17@cyberchimps.com', '858-793-2264', 'Burning Wood', 'San Diego', 'CA', '92105', '1972-05-14', false, '[{"department":"NUR","code":"1C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Xymenes', 'Martina', 'Edison', 'medison18@squidoo.com', '415-896-0392', 'Stephen', 'San Francisco', 'CA', '94169', '2010-01-24', false, '[{"department":"BIO","code":"2B"},{"department":"PHYS","code":"1C"},{"department":"MATH","code":"1D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Pace', 'Veronique', 'Pinder', 'vpinder19@buzzfeed.com', '734-526-6196', 'Moland', 'Detroit', 'MI', '48206', '2003-08-19', true, '[{"department":"GEO","code":"4B"},{"department":"CHEM","code":"3D"},{"department":"CIM","code":"1B"},{"department":"HIST","code":"2B"},{"department":"ANTH","code":"1D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Raquela', 'Sebastiano', 'Vials', 'svials1a@aol.com', '561-164-7096', 'Schlimgen', 'West Palm Beach', 'FL', '33416', '2015-10-10', true, '[{"department":"BIO","code":"1C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Fletcher', 'Donavon', 'Kynaston', 'dkynaston1b@g.co', '562-356-8531', 'Monica', 'Whittier', 'CA', '90605', '1994-07-26', true, '[{"department":"BIO","code":"2B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Thedric', 'Hamlin', 'Langabeer', 'hlangabeer1c@networkadvertising.org', '320-959-9831', 'Banding', 'Saint Cloud', 'MN', '56398', '1996-07-04', true, '[{"department":"ANTH","code":"1C"},{"department":"ENG","code":"4C"},{"department":"HUM","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Rip', 'Cleopatra', 'Faraker', 'cfaraker1d@howstuffworks.com', '256-327-4704', 'Maywood', 'Huntsville', 'AL', '35895', '1978-05-26', true, '[{"department":"LANG","code":"1B"},{"department":"ACC","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Jaine', 'Kary', 'Rubica', 'krubica1e@mozilla.org', '518-320-3616', 'Crest Line', 'Albany', 'NY', '12210', '2006-09-04', false, '[{"department":"MUS","code":"1D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Broderic', 'Martica', 'Teasey', 'mteasey1f@amazon.de', '404-195-7594', 'New Castle', 'Atlanta', 'GA', '30392', '1997-06-25', false, '[{"department":"MUS","code":"2B"},{"department":"CHEM","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Goldi', 'Sergeant', 'Spary', 'sspary1g@time.com', '703-871-1210', 'Westridge', 'Washington', 'DC', '20041', '1980-02-02', true, '[{"department":"PSYC","code":"3B"},{"department":"ART","code":"4D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Danell', 'Gabie', 'Casaroli', 'gcasaroli1h@amazon.co.uk', '702-839-3461', 'Transport', 'Las Vegas', 'NV', '89150', '1986-01-31', true, '[{"department":"ACC","code":"2C"},{"department":"ENG","code":"1C"},{"department":"ENV","code":"1A"},{"department":"MATH","code":"1B"},{"department":"CIM","code":"4B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Arluene', 'Lauri', 'Biasotti', 'lbiasotti1i@nbcnews.com', '916-859-8569', 'Atwood', 'Sacramento', 'CA', '94297', '2018-08-18', true, '[{"department":"CRTV","code":"4D"},{"department":"CIM","code":"2A"},{"department":"ANTH","code":"1C"},{"department":"BIO","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Zebedee', 'Robena', 'Pallesen', 'rpallesen1j@histats.com', '412-561-2867', 'Annamark', 'Mc Keesport', 'PA', '15134', '1992-12-24', true, '[{"department":"GEO","code":"4B"},{"department":"CRTV","code":"3A"},{"department":"HIST","code":"3C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Con', 'Joceline', 'Vasic', 'jvasic1k@ovh.net', '419-150-0727', 'Warrior', 'Mansfield', 'OH', '44905', '1985-07-27', true, '[{"department":"BIO","code":"4C"},{"department":"CIM","code":"1B"},{"department":"HIST","code":"3D"},{"department":"ENV","code":"1C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Tuckie', 'Jodee', 'Crosher', 'jcrosher1l@furl.net', '336-859-8412', 'Kedzie', 'Greensboro', 'NC', '27425', '1996-02-26', false, '[{"department":"ANTH","code":"1C"},{"department":"HUM","code":"4A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Oralia', 'Kaleena', 'Dawbery', 'kdawbery1m@engadget.com', '432-425-2349', 'Michigan', 'Odessa', 'TX', '79769', '1982-04-11', true, '[{"department":"ENG","code":"1B"},{"department":"MUS","code":"3B"},{"department":"BUS","code":"3C"},{"department":"MATH","code":"1A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Gabriele', 'Solomon', 'Osborne', 'sosborne1n@nature.com', '206-516-9080', 'Havey', 'Seattle', 'WA', '98185', '1993-10-15', false, '[{"department":"ACC","code":"4C"},{"department":"ACC","code":"1B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Dugald', 'Vernice', 'Basterfield', 'vbasterfield1o@zdnet.com', '919-741-3110', 'Pond', 'Raleigh', 'NC', '27605', '1976-11-26', true, '[{"department":"HIST","code":"4C"},{"department":"CRTV","code":"2A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Keeley', 'Josh', 'Arkle', 'jarkle1p@mapy.cz', '202-575-2593', 'Wayridge', 'Washington', 'DC', '20470', '2012-07-12', true, '[{"department":"HUM","code":"2A"},{"department":"BIO","code":"1C"},{"department":"ENV","code":"3C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Parker', 'Berkeley', 'Scheffler', 'bscheffler1q@google.com.br', '915-850-9225', 'Ruskin', 'El Paso', 'TX', '79968', '2014-02-19', true, '[{"department":"ACC","code":"1B"},{"department":"EECS","code":"1B"},{"department":"CHEM","code":"3A"},{"department":"LANG","code":"3C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Mame', 'Matt', 'Flaherty', 'mflaherty1r@yolasite.com', '661-921-2151', 'Sachs', 'Bakersfield', 'CA', '93311', '1990-05-20', true, '[{"department":"EECS","code":"4B"},{"department":"GEO","code":"1B"},{"department":"CRTV","code":"1B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Hilde', 'Art', 'Rozenzweig', 'arozenzweig1s@timesonline.co.uk', '330-865-2708', 'Moulton', 'Akron', 'OH', '44329', '2014-05-17', true, '[{"department":"ACC","code":"3A"},{"department":"ENV","code":"2B"},{"department":"PHYS","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Teriann', 'Jay', 'Padden', 'jpadden1t@tripod.com', '909-874-1713', 'Park Meadow', 'San Bernardino', 'CA', '92424', '1983-02-27', true, '[{"department":"HUM","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Erda', 'Rudolfo', 'Fransoni', 'rfransoni1u@parallels.com', '605-954-7572', 'Tony', 'Sioux Falls', 'SD', '57110', '1976-12-28', false, '[{"department":"MUS","code":"3A"},{"department":"PSYC","code":"3D"},{"department":"NUR","code":"1C"},{"department":"LANG","code":"2D"},{"department":"ANTH","code":"1C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Gizela', 'Sherman', 'Crocket', 'scrocket1v@istockphoto.com', '352-367-3749', 'Northport', 'Spring Hill', 'FL', '34611', '1986-03-23', true, '[{"department":"ANTH","code":"4C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Tadeas', 'Lexine', 'Guiton', 'lguiton1w@statcounter.com', '770-565-3008', 'Luster', 'Atlanta', 'GA', '31119', '2019-06-17', false, '[{"department":"ASTR","code":"4A"},{"department":"CIM","code":"4D"},{"department":"GEO","code":"3D"},{"department":"ACC","code":"3B"},{"department":"CIM","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Helenka', 'Pier', 'Lamball', 'plamball1x@baidu.com', '517-400-6974', 'Independence', 'Lansing', 'MI', '48901', '1988-10-19', true, '[{"department":"CRTV","code":"1B"},{"department":"PSYC","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Toma', 'Bryan', 'McGee', 'bmcgee1y@amazon.de', '831-392-2917', 'Bultman', 'Salinas', 'CA', '93907', '1986-08-14', false, '[{"department":"CRTV","code":"1D"},{"department":"LANG","code":"1D"},{"department":"BUS","code":"3C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kirby', 'Branden', 'Burridge', 'bburridge1z@craigslist.org', '202-268-2078', 'Lien', 'Washington', 'DC', '20392', '1976-12-05', false, '[{"department":"NUR","code":"2A"},{"department":"HIST","code":"2D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Vasilis', 'Hesther', 'Devall', 'hdevall20@sitemeter.com', '212-344-7467', 'Novick', 'New York City', 'NY', '10203', '1979-10-21', true, '[{"department":"MUS","code":"2A"},{"department":"GEO","code":"2B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Maritsa', 'Benny', 'Knagges', 'bknagges21@umn.edu', '310-378-0228', 'Scott', 'Santa Monica', 'CA', '90410', '1982-12-28', false, '[{"department":"EECS","code":"3C"},{"department":"CS","code":"2B"},{"department":"CS","code":"2C"},{"department":"ACC","code":"1C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Jasen', 'Martyn', 'Ablott', 'mablott22@amazon.co.jp', '304-168-4019', 'Mallard', 'Huntington', 'WV', '25775', '2018-03-08', false, '[{"department":"LANG","code":"3D"},{"department":"ASTR","code":"3C"},{"department":"HUM","code":"2C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kimberley', 'Joseito', 'McEntee', 'jmcentee23@ox.ac.uk', '216-792-4225', 'Cardinal', 'Cleveland', 'OH', '44191', '1985-10-10', false, '[{"department":"BIO","code":"1B"},{"department":"PSYC","code":"4A"},{"department":"BUS","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Karalee', 'Candy', 'Richold', 'crichold24@ox.ac.uk', '630-183-9337', 'Morrow', 'Naperville', 'IL', '60567', '1998-02-23', true, '[{"department":"GEO","code":"1B"},{"department":"HIST","code":"3B"},{"department":"MATH","code":"4B"},{"department":"BIO","code":"4D"},{"department":"MUS","code":"4C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Orsa', 'Eleanora', 'Trivett', 'etrivett25@wordpress.org', '503-557-1491', 'Maple Wood', 'Portland', 'OR', '97232', '2011-06-06', false, '[{"department":"CIS","code":"1C"},{"department":"LANG","code":"4C"},{"department":"ENG","code":"1D"},{"department":"HIST","code":"1A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kalvin', 'Hi', 'Segrave', 'hsegrave26@jigsy.com', '970-600-1826', 'Rusk', 'Grand Junction', 'CO', '81505', '1996-07-27', false, '[{"department":"EECS","code":"4C"},{"department":"EECS","code":"1D"},{"department":"CRTV","code":"2A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Ardelle', 'Laura', 'Barabisch', 'lbarabisch27@uiuc.edu', '802-644-8227', 'Sunbrook', 'Montpelier', 'VT', '05609', '1985-06-29', false, '[{"department":"PSYC","code":"1A"},{"department":"MATH","code":"3C"},{"department":"PHYS","code":"4C"},{"department":"CRTV","code":"1A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Alane', 'Vic', 'Iceton', 'viceton28@google.nl', '214-582-7978', 'Vidon', 'Dallas', 'TX', '75287', '2008-04-01', false, '[{"department":"HIST","code":"2D"},{"department":"LANG","code":"3C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Jamie', 'Aida', 'Loins', 'aloins29@wordpress.com', '810-480-6159', 'Dorton', 'Flint', 'MI', '48555', '2011-12-03', true, '[{"department":"ECON","code":"1D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Genevra', 'Con', 'Batchelor', 'cbatchelor2a@digg.com', '719-566-9894', 'Golf View', 'Colorado Springs', 'CO', '80945', '2000-12-15', false, '[{"department":"NUR","code":"2B"},{"department":"PHYS","code":"1B"},{"department":"CHEM","code":"2B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Terrill', 'Natty', 'Gossipin', 'ngossipin2b@bigcartel.com', '917-649-7408', 'Schlimgen', 'New York City', 'NY', '10270', '1975-03-30', false, '[{"department":"ACC","code":"2D"},{"department":"ECON","code":"2B"},{"department":"ART","code":"4A"},{"department":"BUS","code":"1C"},{"department":"CS","code":"4D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Archer', 'Zola', 'Dyett', 'zdyett2c@feedburner.com', '765-963-4709', 'Ramsey', 'Crawfordsville', 'IN', '47937', '2010-11-04', true, '[{"department":"MUS","code":"2C"},{"department":"ASTR","code":"1A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Briggs', 'Emylee', 'Brocket', 'ebrocket2d@miibeian.gov.cn', '612-604-7574', 'Coolidge', 'Minneapolis', 'MN', '55487', '1987-02-06', true, '[{"department":"GEO","code":"4C"},{"department":"ASTR","code":"2B"},{"department":"BUS","code":"2D"},{"department":"ENG","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Alfred', 'Hagen', 'Toun', 'htoun2e@jigsy.com', '414-440-4826', 'Raven', 'Milwaukee', 'WI', '53220', '1988-05-08', true, '[{"department":"CIM","code":"1B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Bernard', 'Shurlock', 'Loxley', 'sloxley2f@jiathis.com', '518-214-1466', 'Springs', 'Albany', 'NY', '12210', '1973-05-09', false, '[{"department":"BIO","code":"3D"},{"department":"BIO","code":"2C"},{"department":"BIO","code":"1B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Sarita', 'Ilise', 'Cardoe', 'icardoe2g@hp.com', '225-931-8982', 'Almo', 'Baton Rouge', 'LA', '70883', '2019-02-13', false, '[{"department":"HUM","code":"3B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Merrel', 'Ailis', 'Antoniat', 'aantoniat2h@amazon.com', '804-560-9592', 'Summerview', 'Richmond', 'VA', '23272', '1999-12-16', false, '[{"department":"CHEM","code":"2B"},{"department":"MATH","code":"3D"},{"department":"PSYC","code":"4B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Gregorio', 'Brittani', 'Goade', 'bgoade2i@geocities.com', '321-996-3614', 'Riverside', 'Orlando', 'FL', '32813', '2006-04-25', false, '[{"department":"LANG","code":"4C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Fayth', 'Yolanthe', 'Stempe', 'ystempe2j@cocolog-nifty.com', '215-205-9938', 'Homewood', 'Philadelphia', 'PA', '19131', '2006-02-14', true, '[{"department":"ECON","code":"4C"},{"department":"EECS","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Frazer', 'Joannes', 'Mc Andrew', 'jmcandrew2k@yellowpages.com', '615-183-5323', 'Lakewood', 'Nashville', 'TN', '37235', '2018-09-26', true, '[{"department":"ASTR","code":"2D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Shay', 'Merola', 'Lavigne', 'mlavigne2l@tumblr.com', '801-236-2740', 'Arkansas', 'Salt Lake City', 'UT', '84152', '2017-02-21', true, '[{"department":"CS","code":"4D"},{"department":"ASTR","code":"1D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Martha', 'Tabbie', 'Shapter', 'tshapter2m@bbb.org', '775-594-3840', 'Chinook', 'Reno', 'NV', '89510', '1973-10-01', false, '[{"department":"PSYC","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Hillyer', 'Burg', 'Linturn', 'blinturn2n@zimbio.com', '251-967-3283', 'Sugar', 'Mobile', 'AL', '36628', '2004-04-13', true, '[{"department":"DES","code":"1A"},{"department":"BIO","code":"4C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Brendis', 'Cherianne', 'Kittoe', 'ckittoe2o@apache.org', '405-696-3356', 'Schlimgen', 'Oklahoma City', 'OK', '73179', '1987-02-05', false, '[{"department":"CIS","code":"3C"},{"department":"CRTV","code":"4A"},{"department":"ENG","code":"1D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Anna', 'Leonhard', 'Sanchez', 'lsanchez2p@fastcompany.com', '318-742-3739', 'Tennessee', 'Shreveport', 'LA', '71137', '2021-03-07', false, '[{"department":"CS","code":"2D"},{"department":"MATH","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Cirilo', 'Dwight', 'Camillo', 'dcamillo2q@imageshack.us', '757-142-6207', 'Colorado', 'Newport News', 'VA', '23605', '2012-12-01', true, '[{"department":"CRTV","code":"3B"},{"department":"ENV","code":"4B"},{"department":"ENG","code":"4D"},{"department":"HUM","code":"4C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kora', 'Layton', 'Giblett', 'lgiblett2r@cocolog-nifty.com', '203-371-9024', 'Katie', 'Bridgeport', 'CT', '06673', '1980-10-14', true, '[{"department":"PSYC","code":"3C"},{"department":"DES","code":"2A"},{"department":"CIM","code":"1C"}]');
