create table Faculty (
	firstName VARCHAR(50),
	middleName VARCHAR(50),
	lastName VARCHAR(50),
	email VARCHAR(50),
	telephone VARCHAR(50),
	street VARCHAR(50),
	city VARCHAR(50),
	state VARCHAR(50),
	zip VARCHAR(50),
	hireDate DATE,
	isTenured VARCHAR(50),
	taughtCourses VARCHAR(255)
);
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Kizzie', 'Mitchell', 'Meechan', 'mmeechan0@walmart.com', '419-407-6259', 'Old Gate', 'Toledo', 'OH', '43635', '1984-02-01', true, '[{"department":"HUM","code":"4D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Bernardo', 'Julietta', 'Rudgerd', 'jrudgerd1@mozilla.org', '760-775-3457', 'Summer Ridge', 'San Diego', 'CA', '92121', '1994-01-11', false, '[{"department":"ASTR","code":"4D"},{"department":"ENG","code":"3D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Renata', 'Burlie', 'Gaunt', 'bgaunt2@microsoft.com', '559-478-2711', 'Milwaukee', 'Fullerton', 'CA', '92640', '1983-10-02', true, '[{"department":"CIM","code":"2A"},{"department":"ECON","code":"1B"},{"department":"CIS","code":"3C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Jennee', 'Sosanna', 'Martinot', 'smartinot3@xrea.com', '862-187-9190', 'Ryan', 'Paterson', 'NJ', '07544', '2020-10-11', true, '[{"department":"HUM","code":"1D"},{"department":"BIO","code":"3D"},{"department":"CRTV","code":"1B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Duff', 'Fayina', 'Sergison', 'fsergison4@ovh.net', '617-519-1154', 'Roth', 'Boston', 'MA', '02283', '2020-08-02', true, '[{"department":"DES","code":"3C"},{"department":"EECS","code":"4D"},{"department":"CRTV","code":"3B"},{"department":"ART","code":"2D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Tiphanie', 'Midge', 'Matisse', 'mmatisse5@buzzfeed.com', '801-351-7185', 'La Follette', 'Salt Lake City', 'UT', '84110', '1997-04-12', true, '[{"department":"MUS","code":"1A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Eda', 'Jocelyn', 'Diggle', 'jdiggle6@house.gov', '209-699-3618', 'Moland', 'Modesto', 'CA', '95354', '1992-11-26', true, '[{"department":"CS","code":"1B"},{"department":"ANTH","code":"2C"},{"department":"BUS","code":"2C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Melessa', 'Wells', 'Maidstone', 'wmaidstone7@yelp.com', '406-758-2140', 'Jenifer', 'Missoula', 'MT', '59806', '2017-09-12', false, '[{"department":"HUM","code":"4D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Loralyn', 'Natalee', 'Cromar', 'ncromar8@etsy.com', '915-657-9183', 'Clyde Gallagher', 'El Paso', 'TX', '79989', '2001-03-09', false, '[{"department":"LANG","code":"2B"},{"department":"ENV","code":"2C"},{"department":"PSYC","code":"1A"},{"department":"ANTH","code":"4A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Julina', 'Joellyn', 'Coupar', 'jcoupar9@bbb.org', '617-476-2511', 'Cambridge', 'Boston', 'MA', '02203', '1994-03-18', false, '[{"department":"CS","code":"1C"},{"department":"CIS","code":"4C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Penny', 'Leone', 'Riquet', 'lriqueta@ycombinator.com', '719-956-8785', 'Melvin', 'Colorado Springs', 'CO', '80935', '1991-11-21', true, '[{"department":"ANTH","code":"1C"},{"department":"ENG","code":"3C"},{"department":"ACC","code":"3D"},{"department":"PSYC","code":"3C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Bradney', 'Jody', 'Trapp', 'jtrappb@microsoft.com', '215-333-9346', 'Luster', 'Philadelphia', 'PA', '19120', '2003-12-18', false, '[{"department":"ECON","code":"4D"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Anjanette', 'Zilvia', 'Bravery', 'zbraveryc@umn.edu', '510-678-5730', 'Nova', 'Irvine', 'CA', '92612', '1988-05-31', true, '[{"department":"CHEM","code":"4C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Caril', 'Lonni', 'Lardeux', 'llardeuxd@jimdo.com', '810-303-0217', 'Lighthouse Bay', 'Flint', 'MI', '48505', '2008-11-26', false, '[{"department":"CS","code":"4A"},{"department":"ASTR","code":"4C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Brinna', 'Moina', 'Marcinkowski', 'mmarcinkowskie@google.co.jp', '419-505-6495', 'Hooker', 'Toledo', 'OH', '43610', '1996-12-16', false, '[{"department":"LANG","code":"4C"},{"department":"LANG","code":"4D"},{"department":"PSYC","code":"1B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Magdaia', 'Beauregard', 'Gadault', 'bgadaultf@livejournal.com', '774-464-9330', 'Homewood', 'Worcester', 'MA', '01610', '2004-11-12', false, '[{"department":"NUR","code":"1A"},{"department":"EECS","code":"2A"},{"department":"HIST","code":"4B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Aindrea', 'Wade', 'Ormshaw', 'wormshawg@w3.org', '202-954-9102', 'Evergreen', 'Washington', 'DC', '20456', '1999-08-21', false, '[{"department":"LANG","code":"2C"},{"department":"ART","code":"4D"},{"department":"ACC","code":"2D"},{"department":"CIM","code":"4B"},{"department":"DES","code":"3A"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Valaree', 'Marie-ann', 'Exell', 'mexellh@telegraph.co.uk', '952-556-8360', 'East', 'Young America', 'MN', '55557', '1979-12-04', true, '[{"department":"LANG","code":"3C"},{"department":"BUS","code":"1B"},{"department":"ART","code":"3A"},{"department":"CIM","code":"3A"},{"department":"ASTR","code":"1C"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Vitia', 'Jerad', 'Marmion', 'jmarmioni@mail.ru', '716-635-9566', 'Pond', 'Buffalo', 'NY', '14205', '2010-04-28', true, '[{"department":"MUS","code":"3D"},{"department":"MUS","code":"2A"},{"department":"CRTV","code":"4A"},{"department":"BIO","code":"4B"}]');
insert into Faculty (firstName, middleName, lastName, email, telephone, street, city, state, zip, hireDate, isTenured, taughtCourses) values ('Corene', 'Rolf', 'Axworthy', 'raxworthyj@unesco.org', '860-903-0816', 'Melvin', 'Hartford', 'CT', '06145', '1975-09-28', false, '[{"department":"CIS","code":"4C"},{"department":"DES","code":"1C"},{"department":"CS","code":"2C"}]');
