create table Students (
	firstName VARCHAR(50),
	middleName VARCHAR(50),
	lastName VARCHAR(50),
	email VARCHAR(50),
	telephone VARCHAR(50),
	street VARCHAR(50),
	city VARCHAR(50),
	state VARCHAR(50),
	zip VARCHAR(50),
	dob DATE,
	startDate DATE,
	gpa DECIMAL(3,2),
	registeredCourses VARCHAR(255)
);
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Norine', 'Pooh', 'Moring', 'pmoring0@instagram.com', '714-479-3255', 'Sycamore', 'San Jose', 'CA', '95128', '1971-11-30', '1996-03-30', 3.51, '[{"department":"DES","code":"1B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Demetra', 'Kristofor', 'Sparshutt', 'ksparshutt1@themeforest.net', '818-733-3600', 'Sunnyside', 'Burbank', 'CA', '91505', '2000-06-07', '1991-10-28', 2.13, '[{"department":"BUS","code":"2B"},{"department":"NUR","code":"2B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Melita', 'Kirsti', 'Baudin', 'kbaudin2@time.com', '317-457-9392', 'Clyde Gallagher', 'Indianapolis', 'IN', '46221', '1991-03-21', '1985-02-01', 3.57, '[{"department":"CIS","code":"4D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Ruddie', 'Karlen', 'Mackney', 'kmackney3@google.cn', '919-442-2560', 'Washington', 'Durham', 'NC', '27717', '2001-02-18', '2020-02-25', 3.94, '[{"department":"PSYC","code":"4D"},{"department":"DES","code":"2D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Modesty', 'Lane', 'Pelham', 'lpelham4@google.de', '210-629-2058', 'Algoma', 'San Antonio', 'TX', '78225', '1989-05-04', '2018-05-26', 0.15, '[{"department":"BUS","code":"1B"},{"department":"CIS","code":"4A"},{"department":"CIM","code":"3C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Trixie', 'Jasun', 'Cino', 'jcino5@apache.org', '571-432-1711', 'Arapahoe', 'Merrifield', 'VA', '22119', '1991-08-26', '2019-02-26', 2.39, '[{"department":"LANG","code":"4A"},{"department":"ECON","code":"2B"},{"department":"ACC","code":"3D"},{"department":"EECS","code":"4B"},{"department":"PSYC","code":"1D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Inglebert', 'Rodger', 'Cunnane', 'rcunnane6@netscape.com', '208-950-7408', 'Hansons', 'Boise', 'ID', '83705', '2000-12-07', '1975-11-20', 0.45, '[{"department":"NUR","code":"4A"},{"department":"BUS","code":"1D"},{"department":"ART","code":"4C"},{"department":"BUS","code":"3A"},{"department":"GEO","code":"1B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Bert', 'Merilee', 'Badam', 'mbadam7@yolasite.com', '904-937-3309', 'Blaine', 'Jacksonville', 'FL', '32209', '2022-01-14', '2017-04-29', 0.33, '[{"department":"EECS","code":"1B"},{"department":"CIS","code":"2A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Jedediah', 'Sara-ann', 'Ovize', 'sovize8@a8.net', '614-924-9969', 'Laurel', 'Columbus', 'OH', '43210', '2012-01-02', '2005-09-03', 2.0, '[{"department":"MATH","code":"2C"},{"department":"CIS","code":"1A"},{"department":"BUS","code":"2A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Paule', 'Cody', 'Ficken', 'cficken9@aboutads.info', '972-447-1357', 'Iowa', 'Dallas', 'TX', '75246', '1993-01-03', '2017-12-20', 3.65, '[{"department":"ANTH","code":"2C"},{"department":"ENV","code":"3C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Saunder', 'Horacio', 'Petteford', 'hpetteforda@msn.com', '334-910-6397', 'Amoth', 'Montgomery', 'AL', '36134', '1993-05-23', '2017-01-22', 0.89, '[{"department":"ART","code":"4B"},{"department":"CHEM","code":"1B"},{"department":"BUS","code":"4A"},{"department":"HUM","code":"1C"},{"department":"BUS","code":"2C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Josie', 'Gnni', 'McCarrell', 'gmccarrellb@blog.com', '937-302-7179', 'Grasskamp', 'Dayton', 'OH', '45408', '1991-02-17', '1986-12-06', 3.67, '[{"department":"ACC","code":"3C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Kalila', 'Davine', 'Jewiss', 'djewissc@hatena.ne.jp', '571-983-0135', 'Pankratz', 'Arlington', 'VA', '22244', '2012-01-01', '1983-10-07', 2.79, '[{"department":"CS","code":"2C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Gayle', 'Shanta', 'Ewestace', 'sewestaced@state.gov', '806-614-8282', 'Luster', 'Amarillo', 'TX', '79188', '1982-01-25', '1975-10-20', 1.44, '[{"department":"ENG","code":"3A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Lethia', 'Daveen', 'Spieck', 'dspiecke@histats.com', '214-258-4720', 'Old Shore', 'Dallas', 'TX', '75372', '2008-06-18', '1991-03-09', 2.09, '[{"department":"ANTH","code":"1C"},{"department":"ANTH","code":"2A"},{"department":"CS","code":"1C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Chucho', 'Glynn', 'O''Rowane', 'gorowanef@g.co', '505-594-3114', 'Cordelia', 'Albuquerque', 'NM', '87190', '1975-06-23', '2012-05-25', 2.42, '[{"department":"CIS","code":"4A"},{"department":"MUS","code":"2C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Sol', 'Eugenio', 'Larway', 'elarwayg@taobao.com', '941-139-9253', 'Everett', 'Orlando', 'FL', '32819', '2020-12-01', '2019-07-28', 2.13, '[{"department":"ART","code":"4D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Rinaldo', 'Georgi', 'Kem', 'gkemh@msn.com', '727-249-1583', 'Kipling', 'Clearwater', 'FL', '34620', '2014-03-25', '2020-07-02', 2.73, '[{"department":"CS","code":"2B"},{"department":"ART","code":"1D"},{"department":"ENG","code":"3C"},{"department":"CIM","code":"3B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Wyatt', 'Ninnetta', 'Bake', 'nbakei@rambler.ru', '770-678-0088', 'South', 'Marietta', 'GA', '30066', '1972-01-22', '2005-08-23', 1.38, '[{"department":"GEO","code":"4D"},{"department":"CIM","code":"4B"},{"department":"CIS","code":"2C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Leilah', 'Cheslie', 'Glassup', 'cglassupj@nationalgeographic.com', '214-379-4403', 'Duke', 'Dallas', 'TX', '75260', '2003-05-31', '2002-06-10', 2.3, '[{"department":"ENG","code":"4B"},{"department":"CRTV","code":"2A"},{"department":"CRTV","code":"2B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Cullen', 'Rebeca', 'Lavington', 'rlavingtonk@nymag.com', '502-123-8857', 'Glendale', 'Migrate', 'KY', '41905', '1988-08-06', '1978-09-22', 3.37, '[{"department":"CS","code":"3D"},{"department":"MATH","code":"3C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Konrad', 'Lorry', 'Tome', 'ltomel@instagram.com', '310-943-6082', 'Colorado', 'Inglewood', 'CA', '90398', '1982-05-29', '1980-02-23', 1.98, '[{"department":"PSYC","code":"4A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Nadine', 'Ingemar', 'Berwick', 'iberwickm@meetup.com', '717-426-4869', 'Waywood', 'Harrisburg', 'PA', '17105', '2016-12-12', '1994-07-22', 3.93, '[{"department":"CHEM","code":"2D"},{"department":"ANTH","code":"1C"},{"department":"HUM","code":"1B"},{"department":"ENG","code":"1D"},{"department":"ECON","code":"4C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Oren', 'Dotty', 'Woodcraft', 'dwoodcraftn@live.com', '612-500-2306', 'Rockefeller', 'Minneapolis', 'MN', '55487', '1990-03-22', '1980-02-23', 0.27, '[{"department":"ENG","code":"2C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Aeriell', 'Sloan', 'Bebb', 'sbebbo@bloglines.com', '202-131-6769', 'Dryden', 'Washington', 'DC', '20414', '1977-12-19', '1977-07-26', 3.73, '[{"department":"BUS","code":"1C"},{"department":"CIS","code":"2A"},{"department":"BUS","code":"1B"},{"department":"ACC","code":"1B"},{"department":"NUR","code":"3B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Burty', 'Shaylah', 'Aubri', 'saubrip@google.it', '650-467-2067', 'Reinke', 'Redwood City', 'CA', '94064', '1986-11-15', '2010-02-21', 2.69, '[{"department":"CRTV","code":"2C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Odette', 'Sigismond', 'Pinckney', 'spinckneyq@aboutads.info', '941-598-0282', 'Grim', 'Seminole', 'FL', '34642', '1999-12-17', '1985-03-23', 0.95, '[{"department":"ENV","code":"4D"},{"department":"BUS","code":"2A"},{"department":"ART","code":"3A"},{"department":"ANTH","code":"3B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Lisa', 'Angela', 'Lode', 'aloder@utexas.edu', '937-985-7409', 'Pearson', 'Dayton', 'OH', '45414', '2017-11-17', '1988-01-07', 3.06, '[{"department":"CHEM","code":"4A"},{"department":"CIM","code":"3C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Gannon', 'Norina', 'McPhail', 'nmcphails@csmonitor.com', '213-378-2958', 'Ilene', 'Los Angeles', 'CA', '90081', '1981-03-09', '2017-09-30', 2.05, '[{"department":"ASTR","code":"1C"},{"department":"ENV","code":"2A"},{"department":"EECS","code":"4A"},{"department":"MATH","code":"4B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Spenser', 'Heinrik', 'Bust', 'hbustt@google.nl', '801-987-4392', 'Bayside', 'Salt Lake City', 'UT', '84105', '1986-10-22', '2017-01-02', 2.99, '[{"department":"HUM","code":"1D"},{"department":"GEO","code":"3C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Pieter', 'Bryna', 'Gentle', 'bgentleu@uol.com.br', '510-612-9844', 'Randy', 'Berkeley', 'CA', '94712', '1974-09-12', '2005-04-11', 3.69, '[{"department":"ENV","code":"4D"},{"department":"MUS","code":"1B"},{"department":"PSYC","code":"1D"},{"department":"ART","code":"2A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Jacki', 'Hatti', 'Jolin', 'hjolinv@lulu.com', '860-844-3738', 'Jenna', 'West Hartford', 'CT', '06127', '2009-05-25', '1999-04-19', 2.41, '[{"department":"BUS","code":"2A"},{"department":"CS","code":"2D"},{"department":"HUM","code":"2B"},{"department":"DES","code":"2D"},{"department":"MATH","code":"1C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Patti', 'Norina', 'Lambrick', 'nlambrickw@nba.com', '970-623-4675', 'Weeping Birch', 'Grand Junction', 'CO', '81505', '1996-03-16', '2015-01-27', 1.74, '[{"department":"CIM","code":"1A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Brigit', 'Markus', 'Padfield', 'mpadfieldx@google.es', '518-904-5520', 'Morrow', 'Albany', 'NY', '12210', '1995-10-16', '2008-02-27', 0.32, '[{"department":"DES","code":"3B"},{"department":"ENG","code":"3C"},{"department":"CIM","code":"2A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Florina', 'Brinn', 'Sissel', 'bsissely@noaa.gov', '215-577-7773', 'Fremont', 'Philadelphia', 'PA', '19131', '2008-11-26', '1970-05-23', 1.51, '[{"department":"ART","code":"2B"},{"department":"CRTV","code":"2A"},{"department":"CRTV","code":"4C"},{"department":"CIM","code":"1A"},{"department":"CIS","code":"2B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Cassie', 'Arabela', 'Guslon', 'aguslonz@yelp.com', '904-255-0795', 'Fairfield', 'Jacksonville', 'FL', '32236', '2014-07-30', '1991-10-23', 2.21, '[{"department":"ENV","code":"3B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Luther', 'Karola', 'Meriton', 'kmeriton10@blogs.com', '913-574-9647', 'Village', 'Shawnee Mission', 'KS', '66286', '1995-07-15', '1991-06-13', 2.5, '[{"department":"HUM","code":"1A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Hillier', 'Artur', 'Ingram', 'aingram11@dailymail.co.uk', '412-119-2673', 'Forster', 'Pittsburgh', 'PA', '15220', '1997-11-27', '1995-04-27', 0.53, '[{"department":"ASTR","code":"2B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Petr', 'Sly', 'Johncey', 'sjohncey12@issuu.com', '262-884-1847', 'Susan', 'Milwaukee', 'WI', '53210', '2013-12-21', '2015-01-12', 1.49, '[{"department":"HIST","code":"4B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Thacher', 'Darcie', 'Pinnell', 'dpinnell13@utexas.edu', '612-384-9379', 'Chinook', 'Minneapolis', 'MN', '55470', '2006-07-26', '1974-10-29', 1.93, '[{"department":"CRTV","code":"2B"},{"department":"ACC","code":"4C"},{"department":"ECON","code":"1C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Roselle', 'Josefina', 'Attard', 'jattard14@uol.com.br', '415-328-2718', 'Butterfield', 'San Francisco', 'CA', '94147', '1989-02-09', '1979-12-17', 1.59, '[{"department":"HUM","code":"3D"},{"department":"BIO","code":"2B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Lisette', 'Mattheus', 'Tolman', 'mtolman15@nsw.gov.au', '515-527-2434', 'Oak Valley', 'Des Moines', 'IA', '50347', '1993-05-14', '1983-01-01', 1.28, '[{"department":"ACC","code":"3C"},{"department":"ECON","code":"4C"},{"department":"PHYS","code":"4C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Lincoln', 'Gavan', 'Allicock', 'gallicock16@smugmug.com', '518-269-0909', '2nd', 'Albany', 'NY', '12210', '1989-06-27', '1998-03-04', 3.7, '[{"department":"CS","code":"4D"},{"department":"GEO","code":"4B"},{"department":"PSYC","code":"1C"},{"department":"CS","code":"4B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Tiebout', 'Jehu', 'Pecey', 'jpecey17@bizjournals.com', '215-800-2752', 'Carpenter', 'Philadelphia', 'PA', '19172', '1997-06-27', '1976-03-25', 0.18, '[{"department":"CRTV","code":"2A"},{"department":"HIST","code":"2A"},{"department":"HIST","code":"2A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Karlan', 'Robina', 'Ciotto', 'rciotto18@exblog.jp', '713-143-9534', 'Fairview', 'Houston', 'TX', '77223', '1984-12-27', '1993-10-17', 1.58, '[{"department":"CHEM","code":"2A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Frants', 'Dorri', 'Petru', 'dpetru19@arstechnica.com', '619-351-0215', 'Twin Pines', 'San Diego', 'CA', '92153', '2005-12-13', '2009-01-19', 0.02, '[{"department":"EECS","code":"4C"},{"department":"ASTR","code":"4B"},{"department":"ENV","code":"2A"},{"department":"ANTH","code":"3A"},{"department":"CS","code":"3C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Perry', 'Gayle', 'Sadlier', 'gsadlier1a@live.com', '352-758-4528', 'Schiller', 'Ocala', 'FL', '34474', '2010-08-22', '1972-12-03', 3.57, '[{"department":"CS","code":"2B"},{"department":"ACC","code":"1B"},{"department":"ART","code":"3D"},{"department":"EECS","code":"2B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Danette', 'Bobbi', 'Lanchbery', 'blanchbery1b@irs.gov', '901-406-7780', 'Cambridge', 'Memphis', 'TN', '38150', '1989-08-13', '1987-03-22', 2.54, '[{"department":"ANTH","code":"1D"},{"department":"MATH","code":"4C"},{"department":"CIM","code":"3A"},{"department":"ENG","code":"4D"},{"department":"ACC","code":"1B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Johnna', 'Obed', 'Leil', 'oleil1c@bandcamp.com', '562-792-0781', 'Wayridge', 'Long Beach', 'CA', '90840', '1994-10-24', '1997-11-23', 1.24, '[{"department":"MATH","code":"4D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Tamarra', 'Tansy', 'Dowdney', 'tdowdney1d@nyu.edu', '417-804-9022', 'Lighthouse Bay', 'Springfield', 'MO', '65810', '1978-09-13', '2004-07-27', 2.01, '[{"department":"NUR","code":"1D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Corny', 'Babbie', 'Menego', 'bmenego1e@illinois.edu', '971-966-4509', 'Carioca', 'Portland', 'OR', '97255', '1975-12-03', '1999-09-20', 0.13, '[{"department":"ACC","code":"4D"},{"department":"BIO","code":"2B"},{"department":"BIO","code":"4C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Kellyann', 'Jacinta', 'Pelman', 'jpelman1f@nasa.gov', '251-706-6952', 'Bowman', 'Mobile', 'AL', '36628', '1978-06-01', '1978-02-19', 3.44, '[{"department":"PSYC","code":"3B"},{"department":"CHEM","code":"2D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Darcy', 'Aeriell', 'Swinfon', 'aswinfon1g@yandex.ru', '570-618-3161', 'Hoepker', 'Scranton', 'PA', '18514', '2002-12-14', '2008-11-25', 3.87, '[{"department":"HIST","code":"4C"},{"department":"ASTR","code":"3D"},{"department":"MATH","code":"2B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Isaiah', 'Ursala', 'Al Hirsi', 'ualhirsi1h@seattletimes.com', '520-602-0503', 'Fairfield', 'Tucson', 'AZ', '85748', '1999-05-26', '1977-03-28', 1.15, '[{"department":"ACC","code":"2B"},{"department":"GEO","code":"4C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Leland', 'Weider', 'Blundin', 'wblundin1i@dyndns.org', '402-872-7940', 'Glendale', 'Omaha', 'NE', '68110', '2007-06-16', '1978-08-04', 3.24, '[{"department":"MUS","code":"4D"},{"department":"EECS","code":"4B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Killian', 'Eldin', 'Bruniges', 'ebruniges1j@deviantart.com', '214-414-5271', 'Stephen', 'Dallas', 'TX', '75241', '1982-12-27', '1997-07-26', 1.4, '[{"department":"ECON","code":"4B"},{"department":"MATH","code":"2C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Griffy', 'Moritz', 'Willatt', 'mwillatt1k@mayoclinic.com', '617-610-0958', 'Jenna', 'Boston', 'MA', '02298', '2012-07-30', '1983-07-18', 1.5, '[{"department":"ECON","code":"2C"},{"department":"LANG","code":"3C"},{"department":"PHYS","code":"3D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Crissie', 'Augustine', 'Harbach', 'aharbach1l@oracle.com', '570-538-6804', 'Moulton', 'Wilkes Barre', 'PA', '18706', '2007-11-21', '1970-06-15', 0.61, '[{"department":"PHYS","code":"3C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Kalle', 'Esmeralda', 'Tissell', 'etissell1m@blogger.com', '561-289-1709', 'Granby', 'West Palm Beach', 'FL', '33421', '1972-12-15', '2000-07-11', 2.72, '[{"department":"DES","code":"4D"},{"department":"CIM","code":"4D"},{"department":"CRTV","code":"1A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Katharine', 'Martyn', 'Daddow', 'mdaddow1n@ustream.tv', '772-722-7108', 'Carberry', 'Vero Beach', 'FL', '32964', '1993-08-10', '1994-01-06', 3.85, '[{"department":"ACC","code":"4A"},{"department":"EECS","code":"2C"},{"department":"HIST","code":"3A"},{"department":"ECON","code":"3D"},{"department":"BUS","code":"1A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Tarrance', 'Mellisent', 'Leglise', 'mleglise1o@cbslocal.com', '714-484-7899', 'Coleman', 'Garden Grove', 'CA', '92645', '2008-09-25', '1981-11-03', 2.12, '[{"department":"HIST","code":"2B"},{"department":"BUS","code":"1D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Gusta', 'Johann', 'Dalzell', 'jdalzell1p@bluehost.com', '208-175-7908', 'Bowman', 'Boise', 'ID', '83716', '2013-04-13', '1999-08-13', 2.13, '[{"department":"LANG","code":"2A"},{"department":"LANG","code":"3C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Theo', 'Katrina', 'Bedford', 'kbedford1q@i2i.jp', '775-295-7219', 'Mcbride', 'Reno', 'NV', '89550', '2002-11-05', '1977-02-15', 3.36, '[{"department":"DES","code":"3A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Ania', 'Coleman', 'Flucker', 'cflucker1r@chron.com', '515-243-0330', 'Barby', 'Des Moines', 'IA', '50330', '2011-01-03', '2006-04-13', 2.39, '[{"department":"ANTH","code":"1D"},{"department":"HUM","code":"1B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Marcelo', 'Joscelin', 'Payton', 'jpayton1s@goodreads.com', '480-970-2374', 'Briar Crest', 'Apache Junction', 'AZ', '85219', '1995-09-30', '1978-01-10', 3.71, '[{"department":"LANG","code":"1C"},{"department":"HIST","code":"4A"},{"department":"NUR","code":"2C"},{"department":"BIO","code":"3A"},{"department":"NUR","code":"3C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Salomone', 'Lissi', 'Colbertson', 'lcolbertson1t@buzzfeed.com', '602-525-2526', 'Prairie Rose', 'Glendale', 'AZ', '85311', '1972-05-24', '1986-04-23', 0.29, '[{"department":"MUS","code":"2C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Georgiana', 'Gavrielle', 'Fitzroy', 'gfitzroy1u@indiatimes.com', '510-540-2030', 'Glacier Hill', 'Oakland', 'CA', '94616', '2020-03-01', '1984-04-03', 0.82, '[{"department":"NUR","code":"4B"},{"department":"ACC","code":"4B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Rachelle', 'Emery', 'Prosh', 'eprosh1v@ovh.net', '559-982-1990', 'Lighthouse Bay', 'Fresno', 'CA', '93740', '2018-01-20', '1997-08-22', 2.85, '[{"department":"MUS","code":"1A"},{"department":"NUR","code":"2A"},{"department":"CIS","code":"3A"},{"department":"ART","code":"1A"},{"department":"NUR","code":"4B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Zelig', 'Ben', 'Reppaport', 'breppaport1w@theglobeandmail.com', '804-941-3980', '6th', 'Richmond', 'VA', '23203', '1973-09-23', '1993-03-10', 1.95, '[{"department":"LANG","code":"2D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Ingelbert', 'Agathe', 'Haburne', 'ahaburne1x@rediff.com', '786-591-6848', 'Randy', 'Miami', 'FL', '33147', '2016-11-21', '1973-04-06', 3.77, '[{"department":"ENV","code":"1B"},{"department":"ANTH","code":"2D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Benedict', 'Lenora', 'Lantry', 'llantry1y@creativecommons.org', '415-834-7215', 'Wayridge', 'San Francisco', 'CA', '94116', '2002-04-16', '2020-03-24', 3.48, '[{"department":"ANTH","code":"4C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Daria', 'Mitzi', 'Beecraft', 'mbeecraft1z@friendfeed.com', '917-148-2657', 'Lindbergh', 'Bronx', 'NY', '10469', '1980-04-18', '1985-09-02', 1.57, '[{"department":"PHYS","code":"4A"},{"department":"CIS","code":"3D"},{"department":"CIM","code":"4B"},{"department":"ENV","code":"2C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Mordy', 'Thedrick', 'Nodin', 'tnodin20@elpais.com', '202-919-4869', 'Moulton', 'Washington', 'DC', '20046', '1992-02-20', '1972-08-07', 2.41, '[{"department":"EECS","code":"2B"},{"department":"HIST","code":"4A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Mariya', 'Pansy', 'Pinney', 'ppinney21@google.com', '212-610-3030', '6th', 'New York City', 'NY', '10275', '1982-07-03', '2011-01-09', 2.79, '[{"department":"CIS","code":"3A"},{"department":"ART","code":"1D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Lindsey', 'Lorinda', 'Kuschek', 'lkuschek22@umich.edu', '513-878-4824', 'Hansons', 'Cincinnati', 'OH', '45238', '2019-05-01', '2017-07-05', 2.8, '[{"department":"ASTR","code":"1C"},{"department":"GEO","code":"3C"},{"department":"LANG","code":"4B"},{"department":"CRTV","code":"1A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Catharina', 'Aaren', 'Found', 'afound23@creativecommons.org', '315-224-1134', 'Blackbird', 'Syracuse', 'NY', '13251', '2003-02-18', '2021-09-08', 1.27, '[{"department":"NUR","code":"2D"},{"department":"MUS","code":"3B"},{"department":"CS","code":"3D"},{"department":"MUS","code":"3A"},{"department":"PSYC","code":"4A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Austin', 'Burke', 'Yewdale', 'byewdale24@creativecommons.org', '405-840-9545', 'Maple', 'Edmond', 'OK', '73034', '1995-01-09', '1975-06-08', 3.98, '[{"department":"CIS","code":"3C"},{"department":"EECS","code":"3A"},{"department":"PHYS","code":"4B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Zora', 'Tana', 'Martino', 'tmartino25@cisco.com', '915-742-7647', 'Burning Wood', 'El Paso', 'TX', '88541', '2019-01-05', '1983-04-15', 2.53, '[{"department":"EECS","code":"1B"},{"department":"ANTH","code":"4A"},{"department":"EECS","code":"2D"},{"department":"HUM","code":"2B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Ophelie', 'Alistair', 'Randleson', 'arandleson26@weibo.com', '203-703-8747', 'Fair Oaks', 'New Haven', 'CT', '06538', '1988-11-10', '1971-04-22', 1.23, '[{"department":"ANTH","code":"2C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Randee', 'Gray', 'Marini', 'gmarini27@godaddy.com', '718-295-3569', 'David', 'Staten Island', 'NY', '10305', '2016-04-11', '2015-11-13', 1.25, '[{"department":"CS","code":"4A"},{"department":"CIM","code":"4D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Randie', 'Tuckie', 'Corradeschi', 'tcorradeschi28@si.edu', '804-571-3116', 'Graceland', 'Richmond', 'VA', '23220', '1974-03-25', '2004-06-20', 1.87, '[{"department":"ENV","code":"2D"},{"department":"DES","code":"2A"},{"department":"ASTR","code":"2D"},{"department":"PSYC","code":"1B"},{"department":"LANG","code":"3B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Dirk', 'Aida', 'Andryushin', 'aandryushin29@csmonitor.com', '361-303-9158', 'Summer Ridge', 'Corpus Christi', 'TX', '78426', '2009-07-25', '2015-11-23', 0.05, '[{"department":"CRTV","code":"4B"},{"department":"PSYC","code":"1C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Agnella', 'Margalo', 'Baiss', 'mbaiss2a@arizona.edu', '915-878-7963', 'Michigan', 'El Paso', 'TX', '88558', '2001-06-30', '1991-01-30', 3.01, '[{"department":"HUM","code":"4B"},{"department":"HIST","code":"2C"},{"department":"ANTH","code":"3B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Loralie', 'Wynny', 'Maxsted', 'wmaxsted2b@wikispaces.com', '619-444-4161', 'Dawn', 'San Diego', 'CA', '92137', '2005-06-25', '2002-12-06', 2.77, '[{"department":"MATH","code":"4A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Kylie', 'Leia', 'Stockhill', 'lstockhill2c@yelp.com', '601-104-8008', 'Kennedy', 'Hattiesburg', 'MS', '39404', '1975-05-02', '2011-03-05', 0.44, '[{"department":"HUM","code":"2B"},{"department":"ART","code":"4C"},{"department":"PSYC","code":"4C"},{"department":"CHEM","code":"2D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Karisa', 'Gideon', 'Metschke', 'gmetschke2d@skype.com', '210-702-5797', 'Golf Course', 'San Antonio', 'TX', '78215', '1977-03-08', '1970-10-01', 2.02, '[{"department":"HIST","code":"3B"},{"department":"GEO","code":"3A"},{"department":"MATH","code":"2A"},{"department":"PHYS","code":"4C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Cully', 'Murial', 'Videler', 'mvideler2e@qq.com', '919-734-1128', 'Hazelcrest', 'Durham', 'NC', '27717', '1986-02-15', '1986-03-26', 3.97, '[{"department":"ENG","code":"4B"},{"department":"PSYC","code":"1A"},{"department":"BUS","code":"1A"},{"department":"CIM","code":"2D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Kellia', 'Bethanne', 'Del Castello', 'bdelcastello2f@google.nl', '203-253-4217', 'Blue Bill Park', 'Bridgeport', 'CT', '06606', '2002-08-31', '1998-04-11', 2.16, '[{"department":"ENV","code":"2D"},{"department":"ART","code":"3A"},{"department":"ENV","code":"4D"},{"department":"ART","code":"3C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Lowe', 'Keelby', 'Elacoate', 'kelacoate2g@jugem.jp', '202-428-8460', '4th', 'Washington', 'DC', '20005', '2019-10-19', '2000-06-12', 0.68, '[{"department":"ENG","code":"3C"},{"department":"CS","code":"3D"},{"department":"HUM","code":"3D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Jacquenetta', 'Peggy', 'Brasher', 'pbrasher2h@gravatar.com', '415-869-5966', 'Green', 'San Francisco', 'CA', '94164', '1988-02-06', '2019-02-15', 3.31, '[{"department":"CHEM","code":"1D"},{"department":"ECON","code":"2B"},{"department":"ECON","code":"2D"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Riki', 'Wang', 'D''eye', 'wdeye2i@github.io', '571-393-2817', 'Talisman', 'Springfield', 'VA', '22156', '1998-05-28', '1977-03-18', 1.14, '[{"department":"ENG","code":"1A"},{"department":"LANG","code":"2C"},{"department":"CHEM","code":"4C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Rhianna', 'Sashenka', 'Bolsteridge', 'sbolsteridge2j@auda.org.au', '304-244-5791', 'Schurz', 'Charleston', 'WV', '25331', '1997-04-21', '1972-08-26', 1.61, '[{"department":"PHYS","code":"3B"},{"department":"ASTR","code":"1B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Kyle', 'Major', 'Jent', 'mjent2k@g.co', '559-516-4929', 'Oak Valley', 'Fresno', 'CA', '93726', '2014-01-09', '1977-03-29', 3.53, '[{"department":"CRTV","code":"2A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Rachele', 'Augustus', 'Yakubov', 'ayakubov2l@census.gov', '617-776-6086', 'Loftsgordon', 'Boston', 'MA', '02283', '2017-08-14', '1994-01-15', 1.58, '[{"department":"CRTV","code":"1D"},{"department":"ACC","code":"1D"},{"department":"PHYS","code":"4D"},{"department":"CS","code":"1C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Matteo', 'Elvin', 'Janak', 'ejanak2m@oaic.gov.au', '401-674-7533', 'Division', 'Providence', 'RI', '02912', '2015-12-01', '1997-11-02', 1.67, '[{"department":"ACC","code":"2D"},{"department":"PHYS","code":"4B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Claribel', 'Ryon', 'Romaines', 'rromaines2n@wunderground.com', '323-218-8778', 'Hooker', 'Los Angeles', 'CA', '90076', '2004-08-15', '1993-11-26', 3.8, '[{"department":"CRTV","code":"3C"},{"department":"BUS","code":"4A"},{"department":"LANG","code":"3C"},{"department":"NUR","code":"1B"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Peyter', 'Bunny', 'Darcy', 'bdarcy2o@webnode.com', '619-181-8780', 'Portage', 'San Diego', 'CA', '92137', '2014-08-11', '2021-05-22', 0.33, '[{"department":"MUS","code":"1A"},{"department":"BUS","code":"3A"},{"department":"ASTR","code":"4B"},{"department":"GEO","code":"4A"},{"department":"CS","code":"4A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Genvieve', 'Edlin', 'Andrioli', 'eandrioli2p@narod.ru', '402-554-9807', 'Thompson', 'Lincoln', 'NE', '68583', '2021-05-12', '1999-08-30', 3.58, '[{"department":"ACC","code":"1D"},{"department":"BUS","code":"2C"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Lillian', 'Georgetta', 'Crutchley', 'gcrutchley2q@foxnews.com', '812-475-8720', '4th', 'Evansville', 'IN', '47712', '1985-03-12', '1981-02-15', 2.06, '[{"department":"ASTR","code":"2C"},{"department":"BUS","code":"2D"},{"department":"ENG","code":"4C"},{"department":"CHEM","code":"4A"},{"department":"ANTH","code":"4A"}]');
insert into Students (firstName, middleName, lastName, email, telephone, street, city, state, zip, dob, startDate, gpa, registeredCourses) values ('Glynda', 'Beau', 'Rennenbach', 'brennenbach2r@naver.com', '713-719-3028', 'Fallview', 'Spring', 'TX', '77386', '2010-09-29', '1976-03-02', 2.23, '[{"department":"BUS","code":"2C"},{"department":"ART","code":"3A"},{"department":"ECON","code":"3C"}]');
